//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchiffeVersenken.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowHelpPreparation {
            get {
                return ((bool)(this["ShowHelpPreparation"]));
            }
            set {
                this["ShowHelpPreparation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Wins {
            get {
                return ((int)(this["Wins"]));
            }
            set {
                this["Wins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Loses {
            get {
                return ((int)(this["Loses"]));
            }
            set {
                this["Loses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GamesPlayed {
            get {
                return ((int)(this["GamesPlayed"]));
            }
            set {
                this["GamesPlayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FastestWin {
            get {
                return ((int)(this["FastestWin"]));
            }
            set {
                this["FastestWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FastestLost {
            get {
                return ((int)(this["FastestLost"]));
            }
            set {
                this["FastestLost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int BestWin {
            get {
                return ((int)(this["BestWin"]));
            }
            set {
                this["BestWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int WorstLose {
            get {
                return ((int)(this["WorstLose"]));
            }
            set {
                this["WorstLose"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"The battlefield is 10x10 fields tall. Ships can't touch each other and can't be placed diagonal.

There are different kind of ships:

        > 1x Battleship (5 fields tall)
        > 2x Cruisers (4 fields tall)
        > 3x Destroyers (3 fields tall)
        > 4x Submarines (2 fields tall)

Each player can shoot as long as he hits. After a miss, its the other players turn.")]
        public string Rules {
            get {
                return ((string)(this["Rules"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool s_Mine {
            get {
                return ((bool)(this["s_Mine"]));
            }
            set {
                this["s_Mine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int s_MineNum {
            get {
                return ((int)(this["s_MineNum"]));
            }
            set {
                this["s_MineNum"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hold left-mouse-button to drag and drop ships onto the battlefield.\r\n\r\nTurn the m" +
            "ouse-wheel to change the orientation of a ship.\r\n\r\nLeft-click once on an already" +
            " placed ship to detach it and then click+drag to place it somewhere else.")]
        public string HelpText {
            get {
                return ((string)(this["HelpText"]));
            }
        }
    }
}
